### ISSUE TITLE
linking error, can not compile

### ISSUE THREAD

**Issue by michalliu** [godmodelabs/ejecta-v8#22]
MACOS Sierra
NDK r16b

	30/30] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libbgjs.so
	  FAILED: : && /Users/leoliu/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv7-none-linux-androideabi --gcc-toolchain=/Users/leoliu/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/leoliu/Library/Android/sdk/ndk-bundle/sysroot -fPIC -isystem /Users/leoliu/Library/Android/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=16 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11  -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a --sysroot /Users/leoliu/Library/Android/sdk/ndk-bundle/platforms/android-16/arch-arm -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--fix-cortex-a8 -Wl,--exclude-libs,libunwind.a -L/Users/leoliu/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libbgjs.so -o ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libbgjs.so CMakeFiles/bgjs.dir/src/main/cpp/jni/JNIClassInfo.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/jni/JNIClass.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/jni/JNIObject.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/jni/JNIBase.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/jni/JNIWrapper.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/bgjs/BGJSV8Engine.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/bgjs/ClientAndroid.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/utils/mallocdebug.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/bgjs/modules/BGJSGLModule.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/bgjs/BGJSCanvasContext.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/bgjs/BGJSGLView.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/ejecta/EJCanvas/EJCanvasContext.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/ejecta/EJConvert.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/ejecta/EJConvertColorRGBA.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/ejecta/EJCanvas/EJPath.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/ejecta/EJCanvas/EJTexture.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/ejecta/EJCanvas/NdkMisc.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/ejecta/EJCanvas/EJImageData.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/ejecta/EJCanvas/EJFont.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/ejecta/EJCanvas/CGCompat.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/ejecta/EJCanvas/EJCanvasContextScreen.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/lodepng/lodepng.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/v8/JNIV8Marshalling.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/v8/JNIV8ClassInfo.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/v8/JNIV8Wrapper.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/v8/JNIV8Object.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/v8/JNIV8GenericObject.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/v8/JNIV8Array.cpp.o CMakeFiles/bgjs.dir/src/main/cpp/v8/JNIV8Function.cpp.o  ../../../../libs/v8/armeabi-v7a/libv8.a -lGLESv1_CM -lEGL -landroid -llog -latomic -lm "/Users/leoliu/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++.a" && :
	  ../../../../include/v8.h:9471: error: undefined reference to 'v8::V8::DisposeGlobal(unsigned int*)'
	  ../../../../include/v8.h:9380: error: undefined reference to 'v8::HandleScope::CreateHandle(v8::internal::Isolate*, unsigned int)'
	  ../../../../include/v8.h:9471: error: undefined reference to 'v8::V8::DisposeGlobal(unsigned int*)'
	  ../../../../include/v8.h:9424: error: undefined reference to 'v8::V8::GlobalizeReference(v8::internal::Isolate*, unsigned int*)'
	  ../../../../include/v8.h:9503: error: undefined reference to 'v8::V8::MakeWeak(unsigned int*, void*, void (*)(v8::WeakCallbackInfo<void> const&), v8::WeakCallbackType)'
	  ../../../../include/v8.h:9380: error: undefined reference to 'v8::HandleScope::CreateHandle(v8::internal::Isolate*, unsigned int)'
	  ../../../../include/v8.h:906: error: undefined reference to 'v8::EscapableHandleScope::Escape(unsigned int*)'
	  ../../../../include/v8.h:9380: error: undefined reference to 'v8::HandleScope::CreateHandle(v8::internal::Isolate*, unsigned int)'
	  ../../../../include/v8.h:9424: error: undefined reference to 'v8::V8::GlobalizeReference(v8::internal::Isolate*, unsigned int*)'
	  ../../../../include/v8.h:9878: error: undefined reference to 'v8::HandleScope::CreateHandle(v8::internal::NeverReadOnlySpaceObject*, unsigned int)'
	  ../../../../include/v8.h:9380: error: undefined reference to 'v8::HandleScope::CreateHandle(v8::internal::Isolate*, unsigned int)'
	  ../../../../include/v8.h:906: error: undefined reference to 'v8::EscapableHandleScope::Escape(unsigned int*)'
	  ../../../../include/v8.h:906: error: undefined reference to 'v8::EscapableHandleScope::Escape(unsigned int*)'
	  /Users/leoliu/Works/1_Mini_Game/ejecta-v8/src/main/cpp/bgjs/BGJSV8Engine.cpp:576: error: undefined reference to 'v8::FunctionTemplate::New(v8::Isolate*, void (*)(v8::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>, v8::Local<v8::Signature>, int, v8::ConstructorBehavior, v8::SideEffectType)'
	  ../../../../include/v8.h:9471: error: undefined reference to 'v8::V8::DisposeGlobal(unsigned int*)'
	  ../../../../include/v8.h:9424: error: undefined reference to 'v8::V8::GlobalizeReference(v8::internal::Isolate*, unsigned int*)'
	  ../../../../include/v8.h:9471: error: undefined reference to 'v8::V8::DisposeGlobal(unsigned int*)'
	  ../../../../include/v8.h:9424: error: undefined reference to 'v8::V8::GlobalizeReference(v8::internal::Isolate*, unsigned int*)'
	  ../../../../include/v8.h:906: error: undefined reference to 'v8::EscapableHandleScope::Escape(unsigned int*)'
	  /Users/leoliu/Works/1_Mini_Game/ejecta-v8/src/main/cpp/bgjs/BGJSV8Engine.cpp:720: error: undefined reference to 'v8::String::Concat(v8::Isolate*, v8::Local<v8::String>, v8::Local<v8::String>)'
	  /Users/leoliu/Works/1_Mini_Game/ejecta-v8/src/main/cpp/bgjs/BGJSV8Engine.cpp:719: error: undefined reference to 'v8::String::Concat(v8::Isolate*, v8::Local<v8::String>, v8::Local<v8::String>)'
	  /Users/leoliu/Works/1_Mini_Game/ejecta-v8/src/main/cpp/bgjs/BGJSV8Engine.cpp:1053: error: undefined reference to 'v8::FunctionTemplate::New(v8::Isolate*, void (*)(v8::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>, v8::Local<v8::Signature>, int, v8::ConstructorBehavior, v8::SideEffectType)'
	  /Users/leoliu/Works/1_Mini_Game/ejecta-v8/src/main/cpp/bgjs/BGJSV8Engine.cpp:1055: error: undefined reference to 'v8::FunctionTemplate::New(v8::Isolate*, void (*)(v8::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>, v8::Local<v8::Signature>, int, v8::ConstructorBehavior, v8::SideEffectType)'
	  /Users/leoliu/Works/1_Mini_Game/ejecta-v8/src/main/cpp/bgjs/BGJSV8Engine.cpp:1058: error: undefined reference to 'v8::FunctionTemplate::New(v8::Isolate*, void (*)(v8::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>, v8::Local<v8::Signature>, int, v8::ConstructorBehavior, v8::SideEffectType)'
	  /Users/leoliu/Works/1_Mini_Game/ejecta-v8/src/main/cpp/bgjs/BGJSV8Engine.cpp:1086: error: undefined reference to 'v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>, void (*)(v8::Local<v8::String>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<void> const&), v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::Local<v8::AccessorSignature>, v8::SideEffectType, v8::SideEffectType)'
	  /Users/leoliu/Works/1_Mini_Game/ejecta-v8/src/main/cpp/bgjs/BGJSV8Engine.cpp:1089: error: undefined reference to 'v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>, void (*)(v8::Local<v8::String>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<void> const&), v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::Local<v8::AccessorSignature>, v8::SideEffectType, v8::SideEffectType)'
	  /Users/leoliu/Works/1_Mini_Game/ejecta-v8/src/main/cpp/bgjs/BGJSV8Engine.cpp:1092: error: undefined reference to 'v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>, void (*)(v8::Local<v8::String>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<void> const&), v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::Local<v8::AccessorSignature>, v8::SideEffectType, v8::SideEffectType)'
	  /Users/leoliu/Works/1_Mini_Game/ejecta-v8/src/main/cpp/bgjs/BGJSV8Engine.cpp:1095: error: undefined reference to 'v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>, void (*)(v8::Local<v8::String>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<void> const&), v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::Local<v8::AccessorSignature>, v8::SideEffectType, v8::SideEffectType)'
	  ../../../../include/v8.h:9878: error: undefined reference to 'v8::HandleScope::CreateHandle(v8::internal::NeverReadOnlySpaceObject*, unsigned int)'
	  /Users/leoliu/Works/1_Mini_Game/ejecta-v8/src/main/cpp/bgjs/BGJSV8Engine.cpp:1338: error: undefined reference to 'v8::StackTrace::GetFrame(v8::Isolate*, unsigned int) const'
	  /Users/leoliu/Works/1_Mini_Game/ejecta-v8/src/main/cpp/bgjs/BGJSV8Engine.cpp:1378: error: undefined reference to 'v8::StackTrace::GetFrame(v8::Isolate*, unsigned int) const'
	  ../../../../include/v8.h:9878: error: undefined reference to 'v8::HandleScope::CreateHandle(v8::internal::NeverReadOnlySpaceObject*, unsigned int)'
	  ../../../../include/v8.h:9878: error: undefined reference to 'v8::HandleScope::CreateHandle(v8::internal::NeverReadOnlySpaceObject*, unsigned int)'
	  ../../../../include/v8.h:9503: error: undefined reference to 'v8::V8::MakeWeak(unsigned int*, void*, void (*)(v8::WeakCallbackInfo<void> const&), v8::WeakCallbackType)'
	  /Users/leoliu/Works/1_Mini_Game/ejecta-v8/src/main/cpp/bgjs/modules/BGJSGLModule.cpp:770: error: undefined reference to 'v8::Value::BooleanValue(v8::Isolate*) const'
	  /Users/leoliu/Works/1_Mini_Game/ejecta-v8/src/main/cpp/v8/JNIV8Marshalling.cpp:238: error: undefined reference to 'v8::Value::BooleanValue(v8::Isolate*) const'
	  /Users/leoliu/Works/1_Mini_Game/ejecta-v8/src/main/cpp/v8/JNIV8Marshalling.cpp:502: error: undefined reference to 'v8::Value::BooleanValue(v8::Isolate*) const'
	  /Users/leoliu/Works/1_Mini_Game/ejecta-v8/src/main/cpp/v8/JNIV8ClassInfo.cpp:538: error: undefined reference to 'v8::Object::SetAccessor(v8::Local<v8::Context>, v8::Local<v8::Name>, void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<void> const&), v8::MaybeLocal<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::SideEffectType, v8::SideEffectType)'
	  /Users/leoliu/Works/1_Mini_Game/ejecta-v8/src/main/cpp/v8/JNIV8ClassInfo.cpp:543: error: undefined reference to 'v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>, void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<void> const&), v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::Local<v8::AccessorSignature>, v8::SideEffectType, v8::SideEffectType)'
	  /Users/leoliu/Works/1_Mini_Game/ejecta-v8/src/main/cpp/v8/JNIV8ClassInfo.cpp:593: error: undefined reference to 'v8::Object::SetAccessor(v8::Local<v8::Context>, v8::Local<v8::Name>, void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<void> const&), v8::MaybeLocal<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::SideEffectType, v8::SideEffectType)'
	  /Users/leoliu/Works/1_Mini_Game/ejecta-v8/src/main/cpp/v8/JNIV8ClassInfo.cpp:598: error: undefined reference to 'v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>, void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<void> const&), v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::Local<v8::AccessorSignature>, v8::SideEffectType, v8::SideEffectType)'
	  ../../../../include/v8.h:9516: error: undefined reference to 'v8::V8::ClearWeak(unsigned int*)'
	  ../../../../include/v8.h:9503: error: undefined reference to 'v8::V8::MakeWeak(unsigned int*, void*, void (*)(v8::WeakCallbackInfo<void> const&), v8::WeakCallbackType)'
	  ../../../../include/v8.h:9503: error: undefined reference to 'v8::V8::MakeWeak(unsigned int*, void*, void (*)(v8::WeakCallbackInfo<void> const&), v8::WeakCallbackType)'
	  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
	  ninja: build stopped: subcommand failed.
	
	
	* Try:
	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
	
	* Get more help at https://help.gradle.org

**Comment by unverbraucht** [comment]
Thanks for the report. Yes, we updated to a newer v8 without updating the README. Please download the latest precompiled v8 shared libs from [our owncloud](https://unverbraucht.de/index.php/s/5DiMgt9cRVK5d1m) or compile yourself as per the README.

README has been updated.

**Comment by michalliu** [comment]
Thanks, It works
