### ISSUE TITLE
Ejecta-v8 as Cordova Plugin

### ISSUE THREAD

**Issue by jorasso** [godmodelabs/ejecta-v8#5]
Do you have any plans to provide your amazing library as Cordova Plugin?

**Comment by unverbraucht** [comment]
Sorry to get back to you so late. This would not be possible - Cordova is based on WebView (which incorporates V8) and this is V8 without WebView. It would not make sense. If you need the DOM Cordova or any other WebView-based approach is the way to go, if not then this or another embedded JS VM is a good approach.
